INSERT INTO TO_DO_MODEL(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'Priyanshi Agarwal', 'Learn Spring', CURRENT_DATE, FALSE);

INSERT INTO TO_DO_MODEL(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'Priyanshi Agarwal', 'Create To-Do App', CURRENT_DATE, FALSE);

INSERT INTO TO_DO_MODEL(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'Priyanshi Agarwal', 'Get Certified', CURRENT_DATE, FALSE);

INSERT INTO TO_DO_MODEL(ID, USER_NAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'Priyanshi Agarwal', 'Learn React.js', CURRENT_DATE, FALSE);

--h2 is a InMemory database, once disconnected all data will be lost